
/*
  cron { 'install-invoke-puppet-at-reboot':
    command => 'puppet apply /root/pemaster.pp',
    user    => 'root',
    special    => 'reboot',
    ensure => present,
    #unless => '/root/testpath.sh',
  }
  */

$ifcfgeth0 = '
  # Generated by parse-kickstart
DEVICE=eth0
IPV6INIT=no
BOOTPROTO=none
UUID=f9998d7e-9a42-4a8b-88cd-e67897c35df0
ONBOOT=yes
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
NAME="System eth0"
ZONE=work
IPADDR=192.168.1.13
GATEWAY=192.168.1.1
PREFIX=24
DNS1=192.168.1.7
DNS2=192.168.1.5
DNS3=192.168.1.6
'

$testpath = '#!/bin/bash

if [ -d $1 ]; then
    exit 0
else 
    exit 1
fi
'

$peconf = '"console_admin_password": "password"
"puppet_enterprise::puppet_master_host": "%{::trusted.certname}"
"puppet_enterprise::profile::master::code_manager_auto_configure": true
"puppet_enterprise::profile::master::r10k_remote": "git@github.com:Vergiet/control-repo.git"
"puppet_enterprise::profile::master::r10k_private_key": "/etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa"
'

$startinstall = '#!/bin/bash

if [ -d /opt/puppetlabs/server ]; then

    echo "PE already installed"
else 

    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8

    /root/puppet-enterprise-2019.7.0-el-7-x86_64/puppet-enterprise-installer -c /root/pe.conf

fi
'
/* source: https://ask.puppet.com/question/32559/how-to-call-upon-puppet-token-that-has-just-been-generated-to-use-to-unpin-nodes/?comment=32571#post-id-32571 */


$tokengen = "#!/bin/bash

token=$(curl -X POST -H 'Content-Type: application/json' --cert $(/usr/local/bin/puppet config print hostcert) --key $(/usr/local/bin/puppet config print hostprivkey) --cacert $(/usr/local/bin/puppet config print localcacert) -d '{\"login\": \"admin\", \"password\": \"password\", \"lifetime\": \"5y\"}' https://$(hostname -f):4433/rbac-api/v1/auth/token)
mkdir /root/.puppetlabs
echo \$token | awk -F\\\" '{ print \$4 }' > /root/.puppetlabs/token
"

  file { "/etc/sysconfig/network-scripts/ifcfg-eth0" :
    ensure   => present,
    content => $ifcfgeth0,
  }

  file { "/root/testpath.sh" :
    ensure   => present,
    content => $testpath,
    mode => '0655',
  }

  file { "/root/startinstall.sh" :
    ensure   => present,
    content => $startinstall,
    mode => '0655',
  }

  file { "/root/pe.conf" :
    ensure   => present,
    content => $peconf,
    mode => '0644',
  }

  file { "/root/tokengen.sh" :
    ensure   => present,
    content => $tokengen,
    mode => '0655',
  }
  exec { 'pmom01.vrgt.xyz':
    command => "/usr/bin/hostnamectl set-hostname PMoM01.vrgt.xyz",
    unless => "/usr/bin/test `/usr/bin/hostname` = 'pmom01.vrgt.xyz'"
  }

  /*

  exec { 'puppet agent -t 1':
    command => "/usr/local/bin/puppet agent -t",
    subscribe => Exec['/root/startinstall.sh'],
  }

  exec { 'puppet agent -t 2':
    command => "/usr/local/bin/puppet agent -t",
    subscribe => Exec['puppet agent -t 1'],
  }

  */

  exec { 'tokengen':
    command => "/root/tokengen.sh",
    subscribe => File["/root/tokengen.sh"],
  }

  exec { 'Deploy code':
    command => "/opt/puppetlabs/bin/puppet-code deploy production --wait",
    subscribe => Exec['tokengen'],
  }

  reboot { 'after':
    subscribe => [Exec['pmom01.vrgt.xyz']],
  }

  $peurl = "https://s3.amazonaws.com/pe-builds/released/2019.7.0/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz"

  file { "/root/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz" :
      ensure   => present,
      source => $peurl,
  }

  exec { "/root/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz":
    command => "tar zxf /root/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz",
    path => "/usr/bin/",
    unless => '/root/testpath.sh /root/puppet-enterprise-2019.7.0-el-7-x86_64',
    subscribe => [File["/root/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz"], File['/root/testpath.sh']],
  }
/*
  firewall { '100 PE required ports':
    dport  => [22, 443, 4432, 4433, 5432, 8080, 8081, 8140, 8142, 8143, 8170],
    proto  => 'tcp',
    action => 'accept',
    subscribe => Exec["/root/puppet-enterprise-2019.7.0-el-7-x86_64.tar.gz"],
  }
  */

# Firewall['100 PE required ports'], 
  exec { '/root/startinstall.sh':
    unless => '/root/testpath.sh /opt/puppetlabs/server',
    subscribe => [File['/root/testpath.sh'], File['/root/pe.conf']],
  }

file { '/etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa':
ensure => present,
source => '/etc/ssh/ssh_host_rsa_key',
group => 'pe-puppet',
owner => 'pe-puppet',
mode => '0600',
subscribe => Exec['/root/startinstall.sh'],

}

file { '/root/.ssh/id_rsa':
ensure => present,
source => '/etc/ssh/ssh_host_rsa_key',
mode => '0600',
subscribe => Exec['/root/startinstall.sh'],
}


